inherit_gem:
  decidim-dev: rubocop-decidim.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.4
  Exclude:
    - "development_app/**/*"
    - "spec/decidim_dummy_app/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"

Metrics/BlockLength:
  Exclude:
    - "lib/decidim/secure_elections/component.rb"
    - "lib/decidim/secure_elections/admin_engine.rb"
    - "spec/**/*"
